comparison=$(addprefix data/,comparison00.dat\
 comparison01.dat\
 comparison02.dat\
 comparison03.dat\
 comparison04.dat\
 comparison05.dat\
 comparison06.dat)

$(comparison) : code/comparison.py
	python code/comparison.py
