data/manifold/% : code/manifold.py
	cd code && ./manifold.py

data/symmetric/%.dat : code/reconstruct.py
	cd code && ./reconstruct.py

data/critical/%.dat : code/reconstruct.py
	cd code && ./reconstruct.py

data/broken/%.dat : code/reconstruct.py
	cd code && ./reconstruct.py
